Repository YuweAEC/hacktoberfest-playground, pull requests merged in 2024-10, with the labels that each got.

#5 Added a CONTRIBUTORS.md file
  CONTRIBUTORS..md
Labels: Hacktoberfest2024

#6 modifiy hello.cpp
  CPP/hello.cpp
Labels: Hacktoberfest2024

#7 modify hello.c file
  CPP/hello.cpp
Labels: Hacktoberfest2024

#10 Update hello.java
  JAVA/hello.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#11 Made a program to check if a number is odd or even in cpp.
  CPP/oddeven.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted

#12 Add AI-Powered_code_review_Bot
  AI-Powered_code_review_Bot/README.md
  AI-Powered_code_review_Bot/code_review_bot.py
  AI-Powered_code_review_Bot/test_file.py
Labels: Hacktoberfest2024, hacktoberfest-accepted

#14 Created BubbleSort.java
  JAVA/Sorting Methods/BubbleSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#16 Add sorting algorithms in C
  C/Sorting_Algorithms_in_C/BubbleSort.c
  C/Sorting_Algorithms_in_C/BucketSort.c
  C/Sorting_Algorithms_in_C/HeapSort.c
  C/Sorting_Algorithms_in_C/InsertionSort.c
  C/Sorting_Algorithms_in_C/LinearSearch.c
  C/Sorting_Algorithms_in_C/MergeSort.c
  C/Sorting_Algorithms_in_C/QuickSort.c
  C/Sorting_Algorithms_in_C/RadixSort.c
  C/Sorting_Algorithms_in_C/SelectionSort.c
  C/Sorting_Algorithms_in_C/ShellSort.c
  C/Sorting_Algorithms_in_C/TimSort.c
Labels: Hacktoberfest2024, hacktoberfest-accepted

#20 Made a program on single linked list
  DSA/dsa_c/a.exe
  DSA/dsa_c/single_linkedlist.c
Labels: Hacktoberfest2024, hacktoberfest-accepted

#21 Updated the Code
  JAVA/Sorting Methods/CountSort.java
  JAVA/Sorting Methods/SelectionSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#22 Added OOP examples for Encapsulation, Inheritance, Polymorphism, and Abstraction in Java
  JAVA/OOPs_inJAVA/Abstraction.java
  JAVA/OOPs_inJAVA/Encapsulation.java
  JAVA/OOPs_inJAVA/Inheritance.java
  JAVA/OOPs_inJAVA/Polymorphism.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#24 Added InsertionSort.java
  JAVA/Sorting Methods/InsertionSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#26 Add real-time speech recognition and translation system with speech-t…
  Translation-speaker/.idea/.gitignore
  Translation-speaker/.idea/inspectionProfiles/Project_Default.xml
  Translation-speaker/.idea/inspectionProfiles/profiles_settings.xml
  Translation-speaker/.idea/language_translation_app.iml
  Translation-speaker/.idea/misc.xml
  Translation-speaker/.idea/modules.xml
  Translation-speaker/README.md
  Translation-speaker/main.py
  Translation-speaker/translated_audio.mp3
  Translation-speaker/translator_app.py
Labels: enhancement, Hacktoberfest2024, hacktoberfest-accepted

#27 added Binary Search
  C/.vscode/c_cpp_properties.json
  C/.vscode/launch.json
  C/.vscode/settings.json
  Python/LinkedList.py
  Python/Queue.py
  Python/Stack.py
  Python/binary_search.py
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#28 LinkedList program to find a node key-value .
  JAVA/linkedListkeysearch.java
Labels: Hacktoberfest2024, hacktoberfest-accepted

#29 Add Breakout Ball-Game
  Breakout-game/README.md
  Breakout-game/breakout.css
  Breakout-game/breakout.js
  Breakout-game/breakout_bg.png
  Breakout-game/index.html
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#33 Added a menu driven program for Circular Linked List operations
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  C/CircularLinkedList.c
  Python/Queue.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#36 Added Quick Sort method
  JAVA/Sorting Methods/QuickSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#37 Doubly Linked List
  .vscode/settings.json
  C/DoublyLinkedList.c
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#38 Add MergeSort.java
  JAVA/Sorting Methods/MergeSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#41 To find the length of Linked List.
  JAVA/listlength.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#43 Add C dynamic array example
  C/array.c
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#45 Node-Creation in Linked List
  JAVA/nodecreation.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#46 Added solution for median of two sorted arrays in Python
  .gitignore
  Python/median_of_two_sorted_arrays.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#48 Create Add Binary
  Add Binary
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#47 feat added an python dsa question to find the duplicate
  DSA/dsa_python/check_duplicate.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#66 Added double_linkedlist in C
  DSA/dsa_c/a.exe
  DSA/dsa_c/double_linkedlist.c
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#55 Added Anagram question to Java DSA
  .gitignore
  DSA/dsa_java/Anagram/Anagram.java
  DSA/dsa_java/Anagram/README.md
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#70 Added bubblesort in C++
  CPP/bubblesort.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#58 Added Binary Search Algorithm in dsa_java
  DSA/dsa_java/BinarySearch.java
  JAVA/Sorting Methods/BubbleSort.java
  JAVA/Sorting Methods/CountSort.java
  JAVA/Sorting Methods/SelectionSort.java
Labels: enhancement, Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#61 Added sorting Algo in cpp
  hello.cpp
  oddeven.cpp
  sorting.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#68 Added Infix to Postfix Conversion Code
  C/InfixToPostfix.c
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#71 Updated BinarySearch.java in dsa folder because array was not sorted so i sorted the array to implement binary search
  DSA/dsa_java/BinarySearch.java
Labels: enhancement, good first issue, Hacktoberfest2024, hacktoberfest

#69 wanted to add searching algorithms in c
  C/searching algorithms/output/bfs.exe
  C/searching algorithms/output/binarysearch.exe
  C/searching algorithms/output/dfs.exe
  C/searching algorithms/output/linearsearch.exe
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#75 Added Binary_Tree.py
  Python/Binary_Tree.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#74 Added Insertion Sort Algorithm
  CPP/InsertionSort.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#76 Created Heap Sort in java
  JAVA/Sorting Methods/HeapSort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#77 Create netflix clone
  netflix clone
Labels: enhancement, Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#81 Create factorial.py
  Python/factorial.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#79 Added sorting algorithms for directory of C++
  CPP/SORTING_ALGORITHMS/InsertionSort.cpp
  CPP/SORTING_ALGORITHMS/bubblesort.cpp
  CPP/SORTING_ALGORITHMS/bucketsort.cpp
  CPP/SORTING_ALGORITHMS/quicksort.cpp
  CPP/SORTING_ALGORITHMS/selectionsort.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#82 roshankumar
  C/9a.c
  check no is odd even
  index.html
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#89 feat: snake game
  Python/SnakeGamePython/.idea/.gitignore
  Python/SnakeGamePython/.idea/Games1.iml
  Python/SnakeGamePython/.idea/inspectionProfiles/Project_Default.xml
  Python/SnakeGamePython/.idea/inspectionProfiles/profiles_settings.xml
  Python/SnakeGamePython/.idea/misc.xml
  Python/SnakeGamePython/.idea/modules.xml
  Python/SnakeGamePython/README.md
  Python/SnakeGamePython/data/sounds/BoxCat Games - Epic Song.mp3
  Python/SnakeGamePython/data/sounds/smw_coin.wav
  Python/SnakeGamePython/jogo_cobra.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#92 Merge sort in java
  DSA/dsa_java/Fibonnaci.java
  DSA/dsa_java/Mergesort.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#50 Added a feature that increases the ball's speed by 10% each time the player scores 5 points, making the game more challenging as you progress.
  Breakout-game/breakout.js
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#93 DSA concept BinarySearch and Linear Search has been added
  DSA/dsa_java/BinarySearch/.idea/.gitignore
  DSA/dsa_java/BinarySearch/.idea/codeStyles/Project.xml
  DSA/dsa_java/BinarySearch/.idea/codeStyles/codeStyleConfig.xml
  DSA/dsa_java/BinarySearch/.idea/misc.xml
  DSA/dsa_java/BinarySearch/.idea/modules.xml
  DSA/dsa_java/BinarySearch/BinarySearch.iml
  DSA/dsa_java/BinarySearch/BinarySearch.java
  DSA/dsa_java/BinarySearch/BinarySearchAnuj.java
  DSA/dsa_java/BinarySearch/CeilingOfNumb.java
  DSA/dsa_java/BinarySearch/FloorOfNumb.java
  DSA/dsa_java/BinarySearch/OrderAgnosticsBS.java
  DSA/dsa_java/BinarySearch/Test.java
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/.idea/.gitignore
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/.idea/codeStyles/Project.xml
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/.idea/codeStyles/codeStyleConfig.xml
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/.idea/misc.xml
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/.idea/modules.xml
  DSA/dsa_java/BinarySearch/out/production/BinarySearch/com/omkar/BinarySearch/BinarySearch.iml
  DSA/dsa_java/LinearSearch/EvenDigits.java
  DSA/dsa_java/LinearSearch/FindMin.java
  DSA/dsa_java/LinearSearch/Main.java
  DSA/dsa_java/LinearSearch/MaxIn2DArray.java
  DSA/dsa_java/LinearSearch/MaxWealth.java
  DSA/dsa_java/LinearSearch/MinIn2DArray.java
  DSA/dsa_java/LinearSearch/SearchIn2DArray.java
  DSA/dsa_java/LinearSearch/SearchInRange.java
  DSA/dsa_java/LinearSearch/SearchInString.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#96 Added more cpp porgrams by expanding CPP repo
  CPP/Array/Facing the sun.cpp
  CPP/Array/Hash/Max distance between same elements.cpp
  CPP/Array/Hash/Subarray range with given sum.cpp
  CPP/Array/Largest Pair Sum.cpp
  CPP/Array/Majority Vote.cpp
  CPP/Array/Max sum path in two arrays.cpp
  CPP/Array/Maximum Difference.cpp
  CPP/Array/Missing And Repeating.cpp
  CPP/Array/Missing in Array.cpp
  CPP/Array/Nearest Multiple of 10.cpp
  CPP/Array/Not a subset sum.cpp
  CPP/Array/Reorganize The Array.cpp
  CPP/Array/Roof Top.cpp
  CPP/Array/Rotate and delete.cpp
  CPP/Array/Single Number.cpp
  CPP/Array/Sort 0s, 1s and 2s.cpp
  CPP/Array/Sorted Subsequence of size 3.cpp
  CPP/Array/Total Count.cpp
  CPP/Array/Two Smallests in Every Subarray.cpp
  CPP/Array/Two Swaps.cpp
  CPP/Backtracking/N-Queen Problem.cpp
  CPP/DP/Count ways to N'th Stair(Order does not matter).cpp
  CPP/DP/Kadane's Algorithm.cpp
  CPP/DP/Minimal Cost.cpp
  CPP/DP/Minimum Cost Path.cpp
  CPP/DP/Minimum number of deletions and insertions.cpp
  CPP/DP/Smallest window in a string containing all the characters of another string.cpp
  CPP/Graph/Circle of strings.cpp
  CPP/Graph/Find the number of islands.cpp
  CPP/Greedy Algorithm/Minimize the Heights II.cpp
  CPP/Greedy Algorithm/Minimum Jumps.cpp
  CPP/Linked List/Clone a linked list with next and random pointer.cpp
  CPP/Linked List/Count Linked List Nodes.cpp
  CPP/Linked List/Delete Alternate Nodes.cpp
  CPP/Linked List/Deletion and Reverse in Circular Linked List.cpp
  CPP/Linked List/Find length of Loop.cpp
  CPP/Linked List/Linked List Matrix.cpp
  CPP/Linked List/Multiply two linked lists.cpp
  CPP/Linked List/Palindrome Linked List.cpp
  CPP/Linked List/Sort a k sorted doubly linked list.cpp
  CPP/Linked List/Split Linked List Alternatingly.cpp
  CPP/Linked List/XOR Linked List.cpp
  CPP/Mathematics logic algo/Nth Natural Number.cpp
  CPP/Max sum path in two arrays.cpp
  CPP/Queue/K Sized Subarray Maximum.cpp
  CPP/Queue/Minimum Cost of Ropes.cpp
  CPP/SORTING_ALGORITHMS/Sorting Elements of an Array by Frequency.cpp
  CPP/Stack/Longest Valid Parenthesis.cpp
  CPP/String/Longest Prefix Suffix.cpp
  CPP/String/Parenthesis Checker.cpp
  CPP/String/Reverse Words.cpp
  CPP/Tree/Binary Tree to DLL.cpp
  CPP/Tree/Merge two BST 's.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#94 Create rock_paper_scissors_game.py
  Python/rock_paper_scissors_game.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#98 Add java problems
  JAVA/GCD of two numbers/Solution1.java
  JAVA/Remove characters from alphanumeric string/Solution1.java
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#99 Your feature branch
  CPP/DP/Count numbers containing 4.cpp
  CPP/Stack/Implement stack using array.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest

#100 added Turtle_race.py
  turtle_race/Turtle_race.py
Labels: Hacktoberfest2024, hacktoberfest-accepted, hacktoberfest
